### ISSUE TITLE
async invalid syntax

### ISSUE THREAD

**Issue by spaceblnkt** [isaackogan/OmeglePy#3]
Running the quick start code, an error occurs.

`\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\asyncio\base_events.py", line 296

    future = tasks.async(future, loop=self)
                   ^SyntaxError: invalid syntax`

**Comment by spaceblnkt** [comment]
^ uninstalled asyncio. didn't realize it came with python now

**Comment by isaackogan** [comment]
Sounds good, let me know if you need any help
