### ISSUE TITLE
ModuleNotFoundError: No module named 'OmeglePy.ext'

### ISSUE THREAD

**Issue by neo-devnull** [isaackogan/OmeglePy#4]
The ext module is not detected when installing the package from pypi or using pip to install from the repository directly, however when installed with the editable flag it runs fine without issues. 
Python version is 3.9.6

Here is the traceback.
```
Traceback (most recent call last):
  File "/home/neo/work/bots/omegle/main.py", line 1, in <module>
    from OmeglePy import OmegleClient, EventHandler
  File "/home/neo/.var/envs/omegle2/lib/python3.9/site-packages/OmeglePy/__init__.py", line 5, in <module>
    from .ext import *
ModuleNotFoundError: No module named 'OmeglePy.ext'

```

**Comment by isaackogan** [comment]
I guess there's something to be said about testing your work after you push it... I'll fix this and put out a new version today. Thanks for letting me know

**Comment by isaackogan** [comment]
Currently looking into this

**Comment by isaackogan** [comment]
I'm going to trust this PR solves the issues since I'm fresh out of motivation.
